CREATE DATABASE AbsensiDB;
GO

USE AbsensiDB;
GO

CREATE TABLE Karyawan (
    Id INT PRIMARY KEY IDENTITY,
    NIK VARCHAR(20) NULL,
    Nama VARCHAR(100) NOT NULL,
    FaceEmbedding VARBINARY(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE Absensi (
    Id INT PRIMARY KEY IDENTITY,
    KaryawanId INT NOT NULL FOREIGN KEY REFERENCES Karyawan(Id),
    Tanggal DATE NOT NULL,
    JamMasuk TIME NULL,
    JamKeluar TIME NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO